version: '3.8'
  
services:
  # Servizio per l'app NestJS
  nestjs-app:
    build: .
    container_name: TodoApp-NestJS
    ports:
      - "8080:8080"
    env_file:
      - .env.production.local
    depends_on:
      - postgres

  # Servizio per il DB PostgreSQL
  postgres:
    image: postgres:13
    container_name: PostgreSQL
    env_file:
      - .env.production.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
